version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t rolandjurd/template-project:$TAG .
          docker tag rolandjurd/template-project:$TAG rolandjurd/template-project:latest
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push rolandjurd/template-project:$TAG
